### ISSUE TITLE
Gem release dates are wrong

### ISSUE THREAD

**Issue by bquorning** [sinisterchipmunk/genspec#9]
According to https://rubygems.org/gems/genspec/versions, all versions of this gem were released on July 8, 2010. I think the common pattern is to just remove the `s.date` line from gemspec :-)

**Comment by sinisterchipmunk** [comment]
Thanks, I just noticed this myself but had no idea where to look to fix it. I don't think I ever added that to begin with; must have been generated by whatever generator of the era I used. OTOH, I often don't recognize my own code after 6 months -- let alone 6 years -- so who knows? :)
